version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "action-dependencies"

  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "daily"
    labels:
      - "mvn-dependencies"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - "npm-dependencies"
